import { app, BrowserWindow } from 'electron';
import { Client } from 'wwebjs-electron';
import pie from "puppeteer-in-electron";
import puppeteer from "puppeteer-core";
import isDev from 'electron-is-dev'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let whatsappClient: Client

pie.initialize(app)
  .then(() => {
    const createMainWindow = (): BrowserWindow => {
      // Create the browser window.
      const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
          preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
      });

      // and load the index.html of the app.
      mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

      // Open the DevTools.
      mainWindow.webContents.openDevTools();
      return mainWindow
    };
    const createWWebWindow = async (mainWindow: BrowserWindow): Promise<void> => {
      const window = new BrowserWindow({
      })
      window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
      mainWindow.on('close', () => {
        window.close()
      })
      const browser = await pie.connect(app, puppeteer as any);
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      whatsappClient = new Client(browser, window);
      whatsappClient.on('qr', (qr: string) => {
        mainWindow.webContents.send('qrcode', qr)
      });

      whatsappClient.on('ready', () => {
        console.log('Client is ready!');
        mainWindow.webContents.send('connected', true)

      });

      whatsappClient.on('disconnected', () => {
        console.log('Client is disconnected!');
        mainWindow.webContents.send('connected', false)
      });

      whatsappClient.on('auth_failure', (message) => {
        mainWindow.webContents.send('log', message)
      })

      setTimeout(async () => {
        try {
          await whatsappClient.initialize();
        } catch (error) {
          mainWindow.webContents.send('log', JSON.stringify({ error, whatsappClient }))
        }
      }, 1000);

    }

    const main = async () => {
      const mainWindow = createMainWindow()
      await createWWebWindow(mainWindow)

      if (isDev && process.platform === 'win32') {
        // Set the path of electron.exe and your app.
        // These two additional parameters are only available on windows.
        // Setting this is required to get this working in dev mode.
        app.setAsDefaultProtocolClient('wmstatus', process.execPath, [
        ]);
      } else {
        app.setAsDefaultProtocolClient('wmstatus');
      }

      app.on('open-url', function (event, url) {
        const data = decodeURI(url.replace('wmstatus://', ''))
        const contact = data.slice(data.indexOf('contact='), data.indexOf('&message=')).replace('contact=', '')
        const message = data.slice(data.indexOf('message=')).replace('message=', '')
        console.log(contact, message);

        whatsappClient.sendMessage(`${contact}@c.us`, message)
      });

    }
    app.on('ready', main);

    app.on('window-all-closed', () => {
      if (process.platform !== 'darwin') {
        app.quit();
      }
    });

    app.on('activate', async () => {
      // On OS X it's common to re-create a window in the app when the
      // dock icon is clicked and there are no other windows open.
      if (BrowserWindow.getAllWindows().length === 0) {
        await main();
      }
    });
  })
  .catch(err => console.error(err))
